steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 
          'us-west1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/dalle-flow:${SHORT_SHA}', '.']
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-west1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/dalle-flow:${SHORT_SHA}']
options:
  machineType: 'E2_HIGHCPU_32'
images:
  - us-west1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/dalle-flow:${SHORT_SHA}
